#!/usr/bin/env bash
set -euo pipefail

allowed_root_md='^(AGENTS|CLAUDE|CONTRIBUTING|README)\.md$'
forbidden_root_md='(^CHANGELOG\.md$|^ROADMAP\.md$|^PLAN\.md$|^TODO\.md$|_SUMMARY\.md$|_GUIDE\.md$|_FIXES\.md$|_NOTES\.md$|_ROADMAP\.md$)'

fail() {
  echo "policy error: $*" >&2
  exit 1
}

[ -f AGENTS.md ] || fail "AGENTS.md is required"
[ -f CLAUDE.md ] || fail "CLAUDE.md is required"
[ -f README.md ] || fail "README.md is required"
[ -f CONTRIBUTING.md ] || fail "CONTRIBUTING.md is required"
[ -f LICENSE ] || fail "LICENSE is required"
[ -f docs/README.md ] || fail "docs/README.md is required"
[ -f docs/plan/specs.md ] || fail "docs/plan/specs.md is required"
[ -f docs/plan/design.md ] || fail "docs/plan/design.md is required"
[ -f docs/plan/tasks.md ] || fail "docs/plan/tasks.md is required"
[ -f docs/developers/task-logs.md ] || fail "docs/developers/task-logs.md is required"

while IFS= read -r file; do
  name="${file#./}"
  if [[ ! "$name" =~ $allowed_root_md ]]; then
    fail "root Markdown file is not allowed: $name"
  fi
  if [[ "$name" =~ $forbidden_root_md ]]; then
    fail "forbidden root Markdown file: $name"
  fi
done < <(find . -maxdepth 1 -type f -name '*.md' | sort)

if find . -maxdepth 1 -type f -regextype posix-extended -regex './.*(SUMMARY|GUIDE|FIXES|NOTES|ROADMAP)\.md' | grep -q .; then
  fail "forbidden root summary/guide/fix/note/roadmap file found"
fi

if [ -s docs/plan/tasks.md ]; then
  bad_tasks=$(grep -nEv '^- \[[ xX]\] .+' docs/plan/tasks.md || true)
  if [ -n "$bad_tasks" ]; then
    echo "$bad_tasks" >&2
    fail "docs/plan/tasks.md must contain only flat Markdown checkbox lines"
  fi
fi

if grep -RInE 'Co-authored-by:|Generated by|AI-generated|Claude generated|ChatGPT generated' . \
  --exclude-dir=.git --exclude-dir=node_modules --exclude-dir=vendor --exclude-dir=dist --exclude-dir=build \
  --exclude='*.zip' --exclude='verify-policy.sh' | grep -q .; then
  fail "AI/co-author metadata marker found"
fi

echo "Policy checks passed."
echo "Root Markdown:"
find . -maxdepth 1 -type f -name '*.md' -printf '%f\n' | sort
